ChatBot_Website_Project/Mamoon/FitnessTracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
    path("accounts/", include("accounts.urls")),
    path("exercises/", include("exercises.urls")),
    path("workouts/", include("workouts.urls")),
    path("routines/", include("routines.urls")),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ChatBot_Website_Project/Mamoon/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.sign_up, name="sign_up"),
    path('signin/', views.sign_in, name="sign_in"),
    path('logout/', views.log_out, name="log_out"),
]

ChatBot_Website_Project/Mamoon/exercises/urls.py
from django.urls import path
from . import views


app_name = "exercises"

urlpatterns = [
    path("all/", views.all_exercises_view, name="all_exercises_view"),
    path("details/<exercise_id>/", views.exercise_detail_view, name="exercise_detail_view"),
    path("new/exercise/", views.new_exercise_view, name="new_exercise_view"),
    path("update/<exercise_id>/", views.update_exercise_view, name="update_exercise_view"),
    path("delete/<exercise_id>/", views.delete_exercise_view, name="delete_exercise_view"),
    path("search/exercises/", views.search_exercises_view, name="search_exercises_view"),
]

ChatBot_Website_Project/Mamoon/main/urls.py
from django.urls import path
from . import views


app_name = "main"

urlpatterns = [
    path('', views.home_view, name="home_view"),
    path('contact/', views.contact_view, name="contact_view"),
]

ChatBot_Website_Project/Mamoon/routines/urls.py
from django.urls import path
from . import views


app_name = "routines"

urlpatterns = [
    path("all/", views.all_routines_view, name="all_routines_view"),
    path("new/routine/", views.new_routine_view, name="new_routine_view"),
    path("update/<routine_id>/", views.update_routine_view, name="update_routine_view"),
    path("delete/<routine_id>/", views.delete_routine_view, name="delete_routine_view"),
    path("detail/<routine_id>", views.routine_detail_view, name="routine_detail_view"),
    path("search/routines/", views.search_routines_view, name="search_routines_view"),
]

ChatBot_Website_Project/Mamoon/main/models.py
from django.db import models

class Contact(models.Model):
   
    first_name = models.CharField(max_length=1024)
    last_name = models.CharField(max_length=1024)
    email = models.EmailField()
    message = models.TextField()
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.first_name

ChatBot_Website_Project/Mamoon/main/forms.py
from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['first_name', 'last_name', 'email', 'message']

ChatBot_Website_Project/Mamoon/main/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest

from datetime import datetime

from .forms import ContactForm

from routines.models import Routine
from exercises.models import Exercise, Step

from django.contrib import messages


def home_view(request:HttpRequest):
    routines = Routine.objects.filter(is_public=True)
    exercises = Exercise.objects.all()[0:4]

    return render(request, 'main/home.html', {'routines': routines, 'exercises': exercises, 'user': request.user})

def contact_view(request:HttpRequest):
    contact_form = ContactForm()
    
    if request.method == "POST":
        contact_form = ContactForm(request.POST)
        if contact_form.is_valid():
            contact_form.save()
            messages.success(request, "Your Message Has Been Sent Successfully!", "alert-success")
            return redirect('main:home_view')
        else:
            messages.error(request, "Couldn't Send Your Message!", "alert-danger")
            return render(request, "main/contact.html")

    return render(request, 'main/contact.html')

ChatBot_Website_Project/Mamoon/main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>

    <link href="{% static 'css/style.css' %}" rel="stylesheet" />

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

    <link href="https://fonts.googleapis.com/css2?family=Phudu:wght@300..900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300..800;1,300..800&family=Phudu&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Open+Sans:ital,wght@0,300..800;1,300..800&family=Phudu&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Faculty+Glyphic&family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Open+Sans:ital,wght@0,300..800;1,300..800&family=Phudu&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Faculty+Glyphic&family=Funnel+Display:wght@300..800&family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Open+Sans:ital,wght@0,300..800;1,300..800&family=Phudu&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Spicy+Rice&display=swap" rel="stylesheet">
    
    <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet" />

    <title>{% block title %} {% endblock %}</title>
</head>
<body>
    <div class="container-fluid sticky-top pt-3" style="background-color: #43FFAE;">
        <nav class="navbar navbar-expand-lg">
            <div class="container-fluid">
                <a class="navbar-brand" href="/" style="color: #002093;"><h2>Ma'moon</h2></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>

                {% url 'main:contact_view' as contact_url %}
                {% url 'routines:new_routine_view' as new_routine %}
                {% url 'routines:all_routines_view' as all_routines %}
                {% url 'exercises:all_exercises_view' as all_exercises %}
                {% url 'exercises:new_exercise_view' as new_exercise %}

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav me-auto mb-2 mb-lg-0">
<!--               
                    <li class="nav-item">
                      <a {% if request.path == all_exercises %} class="nav-link text-warning bg-dark rounded-5 ps-sm-5 ps-lg-2" {% else %} class="nav-link" {% endif %} href="{{all_exercises}}">All Exercises</a>
                    </li> -->

                    <!-- {% if request.user.is_staff %}
                      <li class="nav-item">
                        <a {% if request.path == new_exercise %} class="nav-link text-warning bg-dark rounded-5 ps-sm-5 ps-lg-2" {% else %} class="nav-link" {% endif %} href="{{new_exercise}}">New Exercises</a>
                      </li>
                    {% endif %} -->

                    <!-- {% if request.user.is_authenticated or request.user.is_staff %}
                      <li class="nav-item">
                        <a {% if request.path == all_routines %} class="nav-link text-warning bg-dark rounded-5 ps-sm-5 ps-lg-2" {% else %} class="nav-link" {% endif %} href="{{all_routines}}">Your All Routines</a>
                      </li>

                      <li class="nav-item">
                        <a {% if request.path == new_routine %} class="nav-link text-warning bg-dark rounded-5 ps-sm-5 ps-lg-2" {% else %} class="nav-link" {% endif %} href="{{new_routine}}">New Routine</a>
                      </li>
                    {% endif %} -->

                    <!-- <li class="nav-item">
                      <a {% if request.path == contact_url %} class="nav-link text-primary bg-white rounded-5 ps-sm-5 ps-lg-2" {% else %} class="nav-link" {% endif %} href="{{contact_url}}">Contact Us</a>
                    </li> -->
                    {% if request.user.is_authenticated %}
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:log_out' %}">Log Out</a>
                      </li>
                    {% else %}
                      <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          Sign up/ Sign in
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                          <li><a class="dropdown-item" href="{% url 'accounts:sign_up' %}">Sign Up</a></li>
                          <li><a class="dropdown-item" href="{% url 'accounts:sign_in' %}?next={{request.path}}">Sign In</a></li>
                        </ul>
                      </li>
                    {% endif %}

                    {% if request.user.is_staff %}
                    <li class="nav-item">
                      <a class="nav-link" >
                        <h5 class="text-dark">
                          Hi {{request.user.first_name}}!
                        </h5>
                      </a> 
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" >
                        <h5 class="text-secondary">
                          Logged in as a staff member
                        </h5>
                      </a> 
                    </li>
                    {% elif request.user.is_authenticated  %}
                    <li class="nav-item">
                      <a class="nav-link" >
                        <h5 class="text-dark">
                          Hi {{request.user.first_name}}!
                        </h5>
                      </a> 
                    </li>
                    {% endif %}

                  </ul>
                  <form class="d-flex" role="search" method="get" action="">
                    <input  class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search" value="{{request.GET.search}}" required minlength="3">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                  </form>
                </div>
              </div>
        </nav>
    </div>



    <main class="p-5">

      {% if messages %}
        {% for message in messages %}
          <div class="alert {{message.tags}} alert-dismissible fade show" role="alert">
            {{message}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endfor %}
      {% endif %}

      {% block content %}

      {% endblock %}
    </main>
    
    <footer class="p-4">
        <!-- <hr class="m-0"/> -->
        <section class="d-flex flex-column justify-content-center align-items-center gap-2">
            <!-- <a href="{% url 'main:contact_view' %}">
                <h2 class="text-center">CONTACT US</h2>
            </a> -->
        </section>
</footer>

<script type="text/javascript">
(function(w, d, s, u) {
    w.RocketChat = function(c) { w.RocketChat._.push(c) }; w.RocketChat._ = []; w.RocketChat.url = u;
    var h = d.getElementsByTagName(s)[0], j = d.createElement(s);
    j.async = true; j.src = 'https://rocketchat-crv29-u37410.vm.elestio.app/livechat/rocketchat-livechat.min.js?_=201903270000';
    h.parentNode.insertBefore(j, h);
})(window, document, 'script', 'https://rocketchat-crv29-u37410.vm.elestio.app/livechat');
</script>

{% if request.user.is_authenticated %}
<script type="text/javascript">
    // The legacy API doesn't always need the RocketChat(function() { ... }) wrapper,
    // but we use it to ensure the livechat object is ready.
    RocketChat(function() {
        // The legacy method to register a guest
        RocketChat.livechat.registerGuest({
            name: '{{ request.user.first_name }}',
            email: '{{ request.user.email }}',
            // For older APIs, custom fields are often passed under a 'customFields' key
            customFields: [
                { key: 'djangoUsername', value: '{{ request.user.username }}', overwrite: true }
            ]
        });

        console.log("Attempted to register guest using legacy API for:", "{{ request.user.username }}");
    });
</script>
{% endif %}

</body>
</html>

ChatBot_Website_Project/Mamoon/main/templates/main/contact.html
{% extends 'main/base.html' %}

{% block title %} Contact Us {% endblock %}

{% block content %}

{% load static %}

<div class="mt-5 d-flex flex-column justify-content-center align-items-center w-100">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-sm-10 col-lg-8 transparent-bg">
                <div class="d-flex flex-column justify-content-start align-items-start">
                    <h2 class="m-0">Can't Wait To Here From YOU!</h2>
                </div>
                <div class="line mb-4"></div>

                <form class="d-flex flex-column gap-4" action="{% url 'main:contact_view' %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="d-flex flex-row justify-content-between gap-2" style="width: 100%;">
                        <input type="text" name="first_name" placeholder="First Name" class="form-control" required/>
                        <input type="text" name="last_name" placeholder="Last Name" class="form-control" required/>
                    </div>
                    <input type="email" name="email" class="form-control" required placeholder="Email Address" />
                    <textarea name="message" class="form-control" required style="height: 100px;"> </textarea>

                    <input type="submit" value="Submit" class="btn" style="background-color: #43FFAE; color: black"/>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

ChatBot_Website_Project/Mamoon/main/templates/main/home.html
{% extends 'main/base.html' %}

{% block title %} Ma'moon Chatbot {% endblock %}

{% block content %}

{% load static %}

{% if request.user == user %}
<div class="d-flex flex-column justify-content-center align-items-center">
    <div class="d-flex w-100 hero"> 
        <div class="row row-cols-1 row-cols-lg-2 g-5">
            <div class="col left-hero">
                <h4 class="text-center" style="line-height: 1.8;">
                    <!-- The  -->
                    <span style="color: #ffbb00;">
                        <!-- FitnessTracker -->

                    </span>  
                    <!-- is designed to help gym enthusiasts log and manage their fitness routines.
                     This system simplifies workout tracking by offering features for creating reusable workout templates,
                      logging workout sessions, and organizing exercises with detailed instructions -->
                </h4>
            </div>
            <div class="col right-hero">
                <div class="d-flex flex-column justify-content-center align-items-center">
                    <h2 class="text-center">
                        <!-- Start creating reusable routines of workouts! -->
                    </h2>
                    {% if request.user.is_authenticated %}
                        <!-- <a href="{% url 'routines:new_routine_view' %}" class="btn btn-warning pe-4 ps-4 mt-3">
                            <h5>Start New Routine</h5>
                        </a> -->
                        <!-- <a href="{% url 'accounts:sign_up' %}" class="btn btn-light pe-5 ps-5 mt-5">
                            <h5>Watch Demo</h5>
                        </a> -->
                    {% else %}
                        <!-- <a href="{% url 'accounts:sign_up' %}" class="btn btn-warning pe-5 ps-5 mt-3">
                            <h5>Sign Up Now</h5>
                        </a> -->
                        <!-- <a href="{% url 'accounts:sign_up' %}" class="btn btn-light pe-5 ps-5 mt-5">
                            <h5>Watch Demo</h5>
                        </a> -->
                  {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% if request.user.is_authenticated %}
        <!-- <div class="line mt-5 mb-5"></div>

        <div class="d-flex flex-column align-items-center">
            <h1>
                Explore Other Routines
            </h1> 
        </div>
        
        {% include 'routines/explore_routines.html' %} -->

    {% endif %}
</div>

<!-- <div class="line mt-5 mb-5"></div> -->

{% endif %}

<div class="d-flex flex-column justify-content-center align-items-center">
    <div class="d-flex flex-column align-items-center">
        <h1>
            <!-- Top Exercises -->
         </h1> 
    </div>
    
    <!-- {%  -->
        <!-- include 'exercises/exercises_list.html'  -->
        <!-- %}     -->

</div>


{% endblock %}