ChatBot_Website_Project/Mamoon/FitnessTracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
    path("accounts/", include("accounts.urls")),
    path("exercises/", include("exercises.urls")),
    path("workouts/", include("workouts.urls")),
    path("routines/", include("routines.urls")),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ChatBot_Website_Project/Mamoon/main/urls.py
from django.urls import path
from . import views


app_name = "main"

urlpatterns = [
    path('', views.home_view, name="home_view"),
    path('contact/', views.contact_view, name="contact_view"),
]

ChatBot_Website_Project/Mamoon/routines/urls.py
from django.urls import path
from . import views


app_name = "routines"

urlpatterns = [
    path("all/", views.all_routines_view, name="all_routines_view"),
    path("new/routine/", views.new_routine_view, name="new_routine_view"),
    path("update/<routine_id>/", views.update_routine_view, name="update_routine_view"),
    path("delete/<routine_id>/", views.delete_routine_view, name="delete_routine_view"),
    path("detail/<routine_id>", views.routine_detail_view, name="routine_detail_view"),
    path("search/routines/", views.search_routines_view, name="search_routines_view"),
]

ChatBot_Website_Project/Mamoon/routines/models.py
from django.db import models
from django.contrib.auth.models import User

class Routine(models.Model):
    name = models.CharField(max_length=256)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    is_public = models.BooleanField(default=True)
    
    def __str__(self) -> str:
        return self.name

ChatBot_Website_Project/Mamoon/workouts/models.py
from django.db import models
from django.contrib.auth.models import User
from exercises.models import Exercise
from routines.models import Routine
from django.utils import timezone

class Workout(models.Model):
    routine = models.ForeignKey(Routine, on_delete=models.CASCADE)
    exercise = models.ForeignKey(Exercise, on_delete=models.CASCADE)
    note = models.TextField(blank=True)
    restTime = models.PositiveIntegerField(blank=True)
    start_time = models.DateTimeField(default=timezone.now)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self) -> str:
        return f'{self.routine.name}-{self.exercise.name}'


class Set(models.Model):
    weight = models.FloatField()
    repetition = models.PositiveIntegerField()
    workout = models.ForeignKey(Workout, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f'{self.workout.routine.name}-{self.workout.exercise.name} set: {self.id}'
     
     
class Done(models.Model):

    set = models.OneToOneField(Set, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

ChatBot_Website_Project/Mamoon/routines/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse

# from .forms import RoutineForm
from .models import Routine

from django.contrib.auth.models import User

from workouts.models import Workout, Set, Done

from exercises.models import Exercise

from django.contrib import messages
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

from django.db import transaction
from django.utils import timezone
    

def all_routines_view(request:HttpRequest):
    if not request.user.is_authenticated:
        messages.warning(request, "Only registered users can see their routines", "alert-warning")
        return redirect("main:home_view")
        
        
    routines = Routine.objects.filter(user=request.user)
        
    page_number = request.GET.get("page", 1)
    paginator = Paginator(routines, 4)
    routines_page = paginator.get_page(page_number)
    
    return render(request, "routines/all_routines.html", {'routines': routines_page})
    
def profile_view(request:HttpRequest, user_id:int):
    user = User.objects.get(pk=user_id)
    routines = Routine.objects.filter(user=user, is_public=True)
        
    return render(request, "routines/profile.html", {'routines': routines, 'user':user})


def routine_detail_view(request:HttpRequest, routine_id:int):
    routine = Routine.objects.get(pk=routine_id)
    
    exercises = Exercise.objects.all()
    checks = Done.objects.all()
    
    workouts = routine.workout_set.all()
    
    return render(request, "routines/routine_details.html", {'routine': routine,
                                                             'checks': checks, 
                                                             'exercises':exercises,
                                                             'workouts': workouts})

@login_required
def new_routine_view(request:HttpRequest):
    
    if request.method == "POST":
        name = request.POST.get("name", "").strip()
        is_public = request.POST.get("is_public") == "1"  
        
        if name:
            with transaction.atomic():
                routine:Routine = Routine(user=request.user, name=request.POST['name'], is_public=is_public)
                routine.save()
                messages.success(request, "Continue To Add Your Workouts!", "alert-success")
                return redirect("routines:routine_detail_view", routine_id=routine.id)
        else:
            print("not valid form", routine.errors)
            messages.error(request, "Couldn't Able To Add The title!", "alert-danger")
    
    return render(request, "routines/new_routine.html")

@login_required
def update_routine_view(request, routine_id):
    routine = Routine.objects.get(pk=routine_id)

    if request.method == "POST":
        name = request.POST.get("name", "").strip()
        is_public = request.POST.get("is_public") == "1" 

        if name:
            with transaction.atomic():
                routine.name = name
                routine.is_public = is_public
                routine.save()
                messages.success(request, "Routine updated successfully!", "alert-success")
                return redirect("routines:routine_detail_view", routine_id=routine.id)
        else:
            messages.error(request, "Couldn't update the routine title!", "alert-danger")

    return render(request, "routines/update_routine.html", {'routine': routine})
    

@login_required
def delete_routine_view(request:HttpRequest,  routine_id:int):
    try:
        routine = Routine.objects.get(pk=routine_id)
        routine.delete()
        messages.success(request, "Deleted Routine Successfully!", "alert-success")
    except Exception as e:
        print(e)
        messages.error(request, "Couldn't Delete Routine!", "alert-danger")
    
    return redirect("routines:all_routines_view")


def search_routines_view(request:HttpRequest):
    if "search" in request.GET and len(request.GET["search"]) >= 3:
        routines = Routine.objects.filter(name__icontains=request.GET["search"])
    
    else:
        messages.error(request, "Couldn't Find Routine!", "alert-danger")
        routines = []
    
    return render(request, "routines/search_routine.html", {'routines': routines,})

    
    
    


    
    
    

ChatBot_Website_Project/Mamoon/routines/templates/routines/all_routines.html
{% extends 'main/base.html' %}

{% block title %} All Routines {% endblock %}

{% block content %}

{% load static %}

<div class="d-flex flex-column justify-content-center align-items-center">
    <div class="transparent-bg d-flex flex-column flex-lg-row justify-content-center align-items-center justify-content-lg-between align-items-lg-center gap-sm-2 gap-md-3 col-lg-8">
        <h1>
            All {{request.user.first_name}} Routines
        </h1>

        <form class="d-flex" role="search" method="get" action="{% url 'routines:search_routines_view' %}">
            <div class="d-flex flex-row justify-content-center align-items-center gap-3">
                <input  class="form-control me-2" type="search" placeholder="Search For Routine" aria-label="Search" name="search"  required minlength="3">


                <input type="submit" value="search" class="btn btn-outline-success"/>
            </div>
        </form>
    </div>
    
    {% include 'routines/routines_list.html' %}
</div>
    

<div class="line mt-5"></div>

<div class="pagination d-flex justify-content-center align-items-center gap-4">
    {% if routines.has_previous %}
        <div class="d-flex gap-1">
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ routines.previous_page_number }}">&laquo; previous</a>
        </div>
    {% endif %}

    <div class="">
        Page {{ routines.number }} of {{ routines.paginator.num_pages }}
    </div>

    {% if routines.has_next %}
        <div class="d-flex gap-4 ">
            <a href="?page={{ routines.next_page_number }}">next &raquo;</a>
            <a href="?page={{ routines.paginator.num_pages }}">last &raquo;</a>
        </div>
    {% endif %}
</div>

{% endblock %}

ChatBot_Website_Project/Mamoon/routines/templates/routines/explore_routines.html
<div class="container">
    <div class="row mt-2 row-cols-1 row-cols-sm-1 row-cols-lg-2 g-5">
        {% if request.user.is_authenticated %}
                {% for routine in routines %}
                    <div class="col">
                        <div class="d-flex flex-column justify-content-start align-items-start h-100 p-4 gap-2 routine_card">
                            <div class="d-flex justify-content-between align-items-center w-100">
                                <a href="{% url 'routines:routine_detail_view' routine.id %}">
                                    <h2>{{routine.name}} </h2>
                                </a>
                                <h5>{{routine.workout_set.all.count}} Workouts</h5>
                            </div>
                            <div class="line"></div>
                            <h3 class="">Exercises</h3>
                            <ol class="row row-cols-1 row-cols-sm-2 row-cols-md-2 row-cols-lg-2  justify-content-between w-100">
                                {% for workout in routine.workout_set.all %}
                                    <li class="col-12">
                                        <p>{{workout.exercise.name}}</p>
                                    </li>
                                {% endfor %}
                            </ol>
                            <div class="line"></div>
                         
                                <h3>By {{routine.user.first_name}}</h3>
              
                        </div>
                    </div>
                {% empty %}
                <div class="col">
                    <div class="d-flex flex-column justify-content-center align-items-center h-100 p-4 gap-2 routine_card">
                        <h3>You have not added any routines yet!</h3>
                        <a href="{% url 'routines:new_routine_view'%}">
                            <button type="button" class="btn btn-warning btn-lg">
                                Add your first routine!
                            </button>
                        </a>
                    </div>
                </div>
                {% endfor %}
        {% endif %}
    </div>
  </div>

ChatBot_Website_Project/Mamoon/routines/templates/routines/new_routine.html
{% extends 'main/base.html' %}

{% block title %} New Routine {% endblock %}

{% block content %}

{% load static %}

<div class="d-flex flex-column justify-content-center align-items-center">
    <h1 class="align-self-center mb-5">
        Create New Workouts Routine
    </h1> 

    <div class="row justify-content-center align-items-center w-100">
        <div class="transparent-bg col-12 col-sm-10 col-lg-5">
            <form class="d-flex flex-column  gap-4 border p-3 rounded" action="{% url 'routines:new_routine_view' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="d-flex flex-column gap-1" style="width: 100%;">
                    <h2 class="">Routine Title</h2>
                    <input type="text" name="name" placeholder="e.g., Chest Day" class="form-control" required/>
                </div>

                <h2 class="">Do you want to make the routine public?</h2>
                <div class="d-flex gap-2">
                    <div class="d-flex flex-column gap-1" style="width: 100%;">
                        <label for="is_public">YES</label>
                        <input type="radio" name="is_public" id="is_public" value="1" class="form-control"  required>
                    </div>
                    <div class="d-flex flex-column gap-1" style="width: 100%;">
                        <label for="is_public">NO</label>
                        <input type="radio" name="is_public" id="is_public" value="0" class="form-control"  required>
                    </div>
                </div>
                

                <input type="submit" value="Go to add workouts!" class="btn form-control" style="background-color: #fcd15c; color: black"/>
            </form>
        </div>
    </div>
</div>

{% endblock %}

ChatBot_Website_Project/Mamoon/routines/templates/routines/routine_details.html
{% extends 'main/base.html' %}

{% block title %} {{routine.name}} Details {% endblock %}

{% block content %}

{% load static %}


<div class="d-flex flex-column justify-content-center align-items-center">
    <div class="d-flex flex-column align-items-center">
        <h1>
             {{routine.name}} Workouts
         </h1> 
    </div>

    
    {% include 'workouts/workouts_list.html' %}
</div>
    

<div class="line mt-3"></div>


{% endblock %}

ChatBot_Website_Project/Mamoon/routines/templates/routines/routines_list.html
<div class="container">
    <div class="row mt-2 row-cols-1 row-cols-sm-1 row-cols-lg-2 g-5">
        {% if request.user.is_authenticated %}
            {% if request.user == user %}
                {% for routine in routines %}
                    <div class="col">
                        <div class="d-flex flex-column justify-content-start align-items-start h-100 p-4 gap-2 routine_card">
                            <div class="d-flex justify-content-between align-items-center w-100">
                                <a href="{% url 'routines:routine_detail_view' routine.id %}">
                                    <h2>{{routine.name}} </h2>
                                </a>
                                <h5>{{routine.workout_set.all.count}} Workouts</h5>
                            </div>
                            <div class="line"></div>
                            <h3 class="">Exercises</h3>
                            <ol class="row row-cols-1 row-cols-sm-2 row-cols-md-3 justify-content-between w-100">
                                {% for workout in routine.workout_set.all %}
                                    <li class="col-12">
                                        <p>{{workout.exercise.name}}</p>
                                    </li>
                                {% endfor %}
                            </ol>
                        </div>
                    </div>
                {% empty %}
                <div class="col">
                    <div class="d-flex flex-column justify-content-center align-items-center h-100 p-4 gap-2 routine_card">
                        <h3>You have not added any routines yet!</h3>
                        <a href="{% url 'routines:new_routine_view'%}">
                            <button type="button" class="btn btn-warning btn-lg">
                                Add your first routine!
                            </button>
                        </a>
                    </div>
                </div>
                {% endfor %}
            {% endif %}
        {% endif %}
    </div>
  </div>

ChatBot_Website_Project/Mamoon/routines/templates/routines/search_routine.html
{% extends 'main/base.html' %}

{% block title %} All Routines {% endblock %}

{% block content %}

{% load static %}

<div class="d-flex flex-column justify-content-center align-items-center">
    <div class="transparent-bg d-flex flex-column flex-lg-row justify-content-center align-items-center justify-content-lg-between align-items-lg-center gap-sm-2 gap-md-3 col-lg-8">
        <div  class="d-flex flex-row justify-content-between align-items-center gap-5">
            <h1>
                Search Results ({{routines.count}})
            </h1>
            <h2 class="">
                 Results for: {{request.GET.search}}
            </h2> 
        </div>

        <form class="d-flex" role="search" method="get" action="{% url 'routines:search_routines_view' %}">
            <div class="d-flex flex-row justify-content-center align-items-center gap-3">
                <input  class="form-control me-2" type="search" placeholder="Search For Routine" aria-label="Search" name="search"  required minlength="3">


                <input type="submit" value="apply" class="btn btn-outline-success"/>
            </div>
        </form>
    </div>
    
    {% include 'routines/routines_list.html' %}
</div>
    

<div class="line mt-5"></div>

{% endblock %}

ChatBot_Website_Project/Mamoon/routines/templates/routines/update_routine.html
{% extends 'main/base.html' %}

{% block title %} Update Routine {% endblock %}

{% block content %}

{% load static %}

<div class="d-flex flex-column justify-content-center align-items-center justify-content-lg-start align-items-lg-start">
    <h1 class="align-self-center align-self-lg-start mb-5">
        Update Your Workout Routine
    </h1> 

    <div class="row justify-content-center justify-content-lg-start w-100">
        <div class="col-12 col-sm-10 col-lg-5">
            <form class="d-flex flex-column gap-4" action="{% url 'routines:update_routine_view' routine.id %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="d-flex flex-column gap-1" style="width: 100%;">
                    <h2 class="">Routine Title</h2>
                    <input type="text" name="name" placeholder="e.g., Chest Day" class="form-control" value="{{ routine.name }}"/>
                </div>

                <h2 class="">Do you want to make the routine public?</h2>
                <div class="d-flex gap-2">
                    <div class="d-flex flex-column gap-1" style="width: 100%;">
                        <label for="is_public_yes">YES</label>
                        <input type="radio" name="is_public" id="is_public_yes" value="1" class="form-control" {% if routine.is_public %} checked {% endif %}>
                    </div>
                    <div class="d-flex flex-column gap-1" style="width: 100%;">
                        <label for="is_public_no">NO</label>
                        <input type="radio" name="is_public" id="is_public_no" value="0" class="form-control" {% if not routine.is_public %} checked {% endif %}>
                    </div>
                </div>

                <input type="submit" value="Update Routine" class="btn form-control" style="background-color: #fcd15c; color: black"/>
            </form>
        </div>
    </div>
</div>

{% endblock %}