ChatBot_Website_Project/Mamoon/FitnessTracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
    path("accounts/", include("accounts.urls")),
    path("exercises/", include("exercises.urls")),
    path("workouts/", include("workouts.urls")),
    path("routines/", include("routines.urls")),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ChatBot_Website_Project/Mamoon/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.sign_up, name="sign_up"),
    path('signin/', views.sign_in, name="sign_in"),
    path('logout/', views.log_out, name="log_out"),
]

ChatBot_Website_Project/Mamoon/exercises/urls.py
from django.urls import path
from . import views


app_name = "exercises"

urlpatterns = [
    path("all/", views.all_exercises_view, name="all_exercises_view"),
    path("details/<exercise_id>/", views.exercise_detail_view, name="exercise_detail_view"),
    path("new/exercise/", views.new_exercise_view, name="new_exercise_view"),
    path("update/<exercise_id>/", views.update_exercise_view, name="update_exercise_view"),
    path("delete/<exercise_id>/", views.delete_exercise_view, name="delete_exercise_view"),
    path("search/exercises/", views.search_exercises_view, name="search_exercises_view"),
]

ChatBot_Website_Project/Mamoon/main/urls.py
from django.urls import path
from . import views


app_name = "main"

urlpatterns = [
    path('', views.home_view, name="home_view"),
    path('contact/', views.contact_view, name="contact_view"),
]

ChatBot_Website_Project/Mamoon/exercises/models.py
from django.db import models

class Exercise(models.Model):
    class WorkoutCategory(models.TextChoices):
        HOME_WORKOUT = 'home', 'Home Workout'
        CLUB_WORKOUT = 'club', 'Club Workout'
        BOTH_WORKOUTS = 'both', 'Home and Club Workouts'
        
    class EquipmentCategory(models.TextChoices):
        NO_EQUIPMENT = 'none', 'No Machine'
        MACHINE = 'machine', 'Machine'
        
    class ExerciseCategory(models.TextChoices):
        STRENGTH = 'strength', 'Strength'
        CARDIO = 'cardio', 'Cardio'
        FLEXIBILITY = 'flexibility', 'Flexibility'
        
    name = models.CharField(max_length=256)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to="media/images/exercises/")
    video_link = models.URLField(blank=True)
    video = models.FileField(upload_to="media/videos/", blank=True)
    
    workout_category = models.CharField(
        max_length=30,
        choices=WorkoutCategory.choices
    )
    equipment_category = models.CharField(
        max_length=30,
        choices=EquipmentCategory.choices
    )
    exercise_category = models.CharField(
        max_length=30,
        choices=ExerciseCategory.choices
    )


    def __str__(self):
        return self.name

class Step(models.Model):
    exercise = models.ForeignKey(Exercise, on_delete=models.CASCADE)
    instruction = models.TextField()
    
    def __str__(self) -> str:
        return f'{self.exercise.name}- step id: {self.id}'

ChatBot_Website_Project/Mamoon/exercises/forms.py
from django import forms
from .models import Exercise


class ExerciseForm(forms.ModelForm):
    class Meta:
        model = Exercise
        fields = "__all__"

ChatBot_Website_Project/Mamoon/exercises/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse

from .models import Exercise, Step
from .forms import ExerciseForm

from django.contrib import messages
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

from django.db import IntegrityError, transaction

from django.contrib import messages


def all_exercises_view(request:HttpRequest):
    exercises = Exercise.objects.all()
    workout_categories = Exercise.WorkoutCategory.choices
    
    page_number = request.GET.get("page", 1)
    paginator = Paginator(exercises, 4)
    exercises_page = paginator.get_page(page_number)
    
    return render(request, "exercises/all_exercises.html", {'exercises': exercises_page, 'workout_categories': workout_categories})

def exercise_detail_view(request:HttpRequest, exercise_id:int):
    exercise = Exercise.objects.get(pk=exercise_id)
    
    return render(request, "exercises/exercise_detail.html", {'exercise': exercise})


def new_exercise_view(request:HttpRequest):

    if not request.user.is_staff:
        messages.success(request, "Only staff can add exercises!", "alert-warning")
        return redirect("main:home_view")

    if request.method == 'POST':
        exercise = Exercise.objects.create(
            name=request.POST['name'],
            description=request.POST.get('description', ''),
            image=request.FILES.get('image'),
            video_link=request.POST.get('video_link', ''),
            video=request.FILES.get('video'),
            workout_category=request.POST['workout_category'],
            equipment_category=request.POST['equipment_category'],
            exercise_category=request.POST['exercise_category'],
        )

        exercise.save()
        messages.success(request, "Exercise added!", "alert-warning")
        return redirect('exercises:all_exercises_view')  

    return render(request, 'exercises/new_exercise.html')


def new_instruction_view(request:HttpRequest, exercise_id:int):

    if not request.user.is_staff:
        messages.success(request, "Only staff can add instructions!", "alert-warning")
        return redirect("main:home_view")

    if request.method == 'POST':
        exercise = Exercise.objects.get(pk=exercise_id)
        instruction = Step.objects.create(
            exercise=exercise,
            instruction=request.POST['instruction']
        )

        instruction.save()
        messages.success(request, "instruction added!", "alert-warning")  

    return redirect('exercises:exercise_detail_view',exercise_id=exercise_id)


def update_exercise_view(request:HttpRequest, exercise_id:int):

    pass

def delete_exercise_view(request:HttpRequest,  exercise_id:int):
    if not request.user.is_staff:
        messages.success(request, "Only staff can delete exercises!", "alert-warning")
        return redirect("main:home_view")
    
    try:
        exercise = Exercise.objects.get(pk=exercise_id)
        exercise.delete()
        messages.success(request, "Deleted Exercise Successfuly!", "alert-success")
    except Exception as e:
        print(e)
        messages.error(request, "Couldn't Delete Exercise!", "alert-danger")
    
    return redirect("main:home_view")


def search_exercises_view(request:HttpRequest):
    workout_categories = Exercise.WorkoutCategory.choices
    exercises = Exercise.objects.all()  

    filter_by = None
    
    if "search" in request.GET and len(request.GET["search"]) >= 3:
        exercises = Exercise.objects.filter(name__icontains=request.GET["search"])
    
            
    if "filter_workout_category" in request.GET and request.GET["filter_workout_category"] != '':
        exercises = exercises.filter(workout_category=request.GET['filter_workout_category'])
        filter_by = request.GET['filter_workout_category']
    
    if not exercises.exists():
        messages.error(request, "Couldn't Find Exercise!", "alert-danger")
        exercises = []
    
    return render(request, "exercises/exercise_search.html", {'exercises': exercises, 
                                                              'workout_categories': workout_categories, 
                                                              'filter_by':filter_by})

    
    
    


    
    
    

ChatBot_Website_Project/Mamoon/exercises/templates/exercises/all_exercises.html
{% extends 'main/base.html' %}

{% block title %} All Exercises {% endblock %}

{% block content %}

{% load static %}

<div class="d-flex flex-column justify-content-center align-items-center">
    <div class="transparent-bg d-flex flex-column flex-lg-row justify-content-center align-items-center justify-content-lg-between align-items-lg-center gap-sm-2 gap-md-3 col-lg-8">
        <h1>
            All Exercises
        </h1>

        <form class="d-flex" role="search" method="get" action="{% url 'exercises:search_exercises_view' %}">
            <div class="d-flex flex-row justify-content-center align-items-center gap-3">
                <input  class="form-control me-2" type="search" placeholder="Search For Exercise" aria-label="Search" name="search"  required minlength="3">
    
                <select name="filter_workout_category " class="form-select">
                    <option >Filter by Workout Category</option>
                    {% for value, display in workout_categories %}
                        <option value="{{value}}">{{ display }}</option>
                    {% endfor %}
                </select>

                <input type="submit" value="apply" class="btn btn-outline-success"/>
            </div>
        </form>
    </div>
    
    {% include 'exercises/exercises_list.html' %}    

</div>
    

<div class="line mt-5"></div>

<div class="pagination d-flex justify-content-center align-items-center gap-4">
    {% if exercises.has_previous %}
        <div class="d-flex gap-1">
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ exercises.previous_page_number }}">&laquo; previous</a>
        </div>
    {% endif %}

    <div class="">
        Page {{ exercises.number }} of {{ exercises.paginator.num_pages }}
    </div>

    {% if exercises.has_next %}
        <div class="d-flex gap-4 ">
            <a href="?page={{ exercises.next_page_number }}">next &raquo;</a>
            <a href="?page={{ exercises.paginator.num_pages }}">last &raquo;</a>
        </div>
    {% endif %}
</div>

{% endblock %}

ChatBot_Website_Project/Mamoon/exercises/templates/exercises/exercise_detail.html
{% extends 'main/base.html' %}

{% block title %} {{exercise.name}} Details {% endblock %}

{% block content %}

{% load static %}

<div class="d-flex flex-column justify-content-center align-items-center">
    <div class="d-flex flex-column align-items-center">
        <h1>
             {{exercise.name}} Exercise
         </h1> 
    </div>

    {% if request.user.is_authenticated %}
        <div class="col-12 col-lg-6 d-flex flex-column align-items-center mt-5">
            <img src="{{exercise.image.url}}" class="rounded-top-5 overflow-hidden" style=" object-fit: cover;"/>
            <div class="line"></div>
        </div>

        <div class="mt-5 d-flex flex-column justify-content-start align-items-start col-12 col-lg-6 routine_card exercise_card p-4">
            <h2>How To Do It:</h2>
            <div class="line mb-4"></div>

            <ol>
                {% for step in exercise.step_set.all %}
                    <h4 class="mb-5">
                        <li>
                            {{step.instruction}}
                        </li>
                    </h4>
                {% endfor %}
            </ol>
        </div>
    {% else %}
        <div class="mt-5 transparent-bg d-flex flex-column  justify-content-center align-items-center gap-sm-2 gap-md-3 col-lg-4">
            <h4 class="text-white">
                Sorry only registers users can view exercise details!
            </h4>
            <h4 class="d-flex justify-content-between col-6">
                <a href="{% url 'accounts:sign_in' %}?next={{request.path}}">
                     <i class="bi bi-box-arrow-in-right"></i> Sign in
                </a>
                <a href="{% url 'accounts:sign_up' %}">
                    Sign up <i class="bi bi-box-arrow-in-left"></i>
                </a>
            </h4>
        </div>
    {% endif %}

</div>
    

<div class="line mt-5"></div>


{% endblock %}

ChatBot_Website_Project/Mamoon/exercises/templates/exercises/exercise_search.html
{% extends 'main/base.html' %}

{% block title %} Exercises {% endblock %}

{% block content %}

{% load static %}

<div class="d-flex flex-column justify-content-center align-items-center">
    <div class="transparent-bg d-flex flex-column flex-lg-row justify-content-center align-items-center justify-content-lg-between align-items-lg-center gap-sm-2 gap-md-3 col-lg-10">
        <div  class="d-flex flex-row justify-content-between align-items-center gap-5">
            <h1>
                Search Results ({{exercises.count}})
            </h1>
            <h2 class="">
                 Results for: {{request.GET.search}}
            </h2> 
        </div>

        <form class="d-flex" role="search" method="get" action="{% url 'exercises:search_exercises_view' %}">
            <div class="d-flex flex-row justify-content-center align-items-center gap-3">
                <input  class="form-control me-2" type="search" placeholder="Search For Exercise" aria-label="Search" name="search" value="{{request.GET.search}}" required minlength="3">
    
                <select name="filter_workout_category" class="form-select">
                    <option value="">Filter By Workout Category</option>
                    {% for value, display in workout_categories %}
                        <option value="{{value}}" {% if request.GET.filter_workout_category == workout_category %} selected {% endif %}>{{ display }}</option>
                    {% endfor %}
                </select>

                <input type="submit" value="apply" class="btn btn-outline-success"/>
            </div>
        </form>
    </div>
    <div class="line mt-5"></div>

    
    {% include 'exercises/exercises_list.html' %}    

</div>
    

<div class="line mt-5"></div>

{% endblock %}

ChatBot_Website_Project/Mamoon/exercises/templates/exercises/exercises_list.html
<div class="container">
    <div class="row mt-2 row-cols-1 row-cols-sm-1 row-cols-lg-2 g-5">
        {% for exercise in exercises %}
            <div class="col">
                <div class="d-flex flex-column justify-content-start align-items-start h-100 p-4 gap-2 routine_card">
                    <div class="d-flex justify-content-between align-items-center w-100">
                        <div class="d-flex justify-content-start align-items-center gap-3 w-100">
                            <img src="{{exercise.image.url}}" class="rounded-circle overflow-hidden" style="width: 80px; height: 80px; object-fit: cover;"/>
                            <a href="{% url 'exercises:exercise_detail_view' exercise.id %}">
                                <h2>{{exercise.name}}</h2>
                            </a>
                        </div>
                        <h4 class="">({{exercise.equipment_category}})</h4>
                    </div>
                    <div class="line"></div>
                    <ul style="list-style-type: square;">
                        <li class="mb-4">
                            <h4>This Exercise Considered {{exercise.get_workout_category_display }}</h4>
                        </li>
                        <li>
                            <h4 class="">It Has {{exercise.step_set.all.count}} Guide Instructions</h4>
                        </li>
                    </ul>
                </div>
            </div>
        {% endfor %}
    </div>
  </div>

ChatBot_Website_Project/Mamoon/exercises/templates/exercises/new_exercise.html
{% extends 'main/base.html' %}

{% block title %} Add/Update Exercise {% endblock %}

{% block content %}
{% load static %}

<div class="d-flex flex-column justify-content-center align-items-center">
    <div class="row justify-content-center w-100">
        <div class="col-12 col-sm-10 col-lg-5">
            <form class="d-flex flex-column gap-4" action="{% url 'exercises:new_exercise_view'%}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
            

                <div class="transparent-bg">
                    <h2>Add Exercise</h2>
                    <div class="d-flex flex-column gap-3 border p-3 rounded">
                        <div class="d-flex flex-column gap-1">
                            <label for="name">Exercise Name</label>
                            <input type="text" name="name" id="name" class="form-control"  required>
                        </div>

                        <div class="d-flex flex-column gap-1">
                            <label for="description">Description</label>
                            <textarea name="description" id="description" class="form-control"></textarea>
                        </div>

                        <div class="d-flex flex-column gap-1">
                            <label for="image">Image</label>
                            <input type="file" name="image" id="image" class="form-control" accept="image/*" required>
                        </div>

                        <div class="d-flex flex-column gap-1">
                            <label for="video_link">Video Link</label>
                            <input type="url" name="video_link" id="video_link" class="form-control" >
                        </div>

                        <div class="d-flex flex-column gap-1">
                            <label for="video">Video File</label>
                            <input type="file" name="video" id="video" class="form-control" accept="video/*">
                        </div>

                        <div class="d-flex flex-column gap-1">
                            <label for="workout_category">Workout Category</label>
                            <select name="workout_category" id="workout_category" class="form-control" required>
                                {% for value, label in exercise.WorkoutCategory.choices %}
                                    <option value="{{ value }}" >{{ label }}</option>
                                {% endfor %}
                            </select>
                        </div>

                        <div class="d-flex flex-column gap-1">
                            <label for="equipment_category">Equipment Category</label>
                            <select name="equipment_category" id="equipment_category" class="form-control" required>
                                {% for value, label in exercise.EquipmentCategory.choices %}
                                    <option value="{{ value }}" >{{ label }}</option>
                                {% endfor %}
                            </select>
                        </div>

                        <div class="d-flex flex-column gap-1">
                            <label for="exercise_category">Exercise Category</label>
                            <select name="exercise_category" id="exercise_category" class="form-control" required>
                                {% for value, label in exercise.ExerciseCategory.choices %}
                                    <option value="{{ value }}">{{ label }}</option>
                                {% endfor %}
                            </select>
                        </div>

                    </div>
                </div>

                <input type="submit" value="Add Exercise" class="btn form-control" style="background-color: #fcd15c; color: black"/>
            </form>
        </div>
    </div>
</div>

{% endblock %}