ChatBot_Website_Project/Mamoon/FitnessTracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
    path("accounts/", include("accounts.urls")),
    path("exercises/", include("exercises.urls")),
    path("workouts/", include("workouts.urls")),
    path("routines/", include("routines.urls")),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ChatBot_Website_Project/Mamoon/main/urls.py
from django.urls import path
from . import views


app_name = "main"

urlpatterns = [
    path('', views.home_view, name="home_view"),
    path('contact/', views.contact_view, name="contact_view"),
]

ChatBot_Website_Project/Mamoon/workouts/urls.py
from django.urls import path
from . import views


app_name = "workouts"

urlpatterns = [
    path("new/workout/<routine_id>", views.new_workout_view, name="new_workout_view"),
    path("update/<workout_id>/", views.update_workout_view, name="update_workout_view"),
    path("delete/<workout_id>/", views.delete_workout_view, name="delete_workout_view"),
    
    path("sets/new/<workout_id>", views.new_set_view, name="new_set_view"),
    path("sets/update/<set_id>/", views.update_set_view, name="update_set_view"),
    path("sets/delete/<set_id>/", views.delete_set_view, name="delete_set_view"),
    path("checks/add/<set_id>/", views.done_set_view, name="done_set_view"),
    path("checks/finsh/<workout_id>/", views.finish_workout_view, name="finish_workout_view"),
]

ChatBot_Website_Project/Mamoon/workouts/models.py
from django.db import models
from django.contrib.auth.models import User
from exercises.models import Exercise
from routines.models import Routine
from django.utils import timezone

class Workout(models.Model):
    routine = models.ForeignKey(Routine, on_delete=models.CASCADE)
    exercise = models.ForeignKey(Exercise, on_delete=models.CASCADE)
    note = models.TextField(blank=True)
    restTime = models.PositiveIntegerField(blank=True)
    start_time = models.DateTimeField(default=timezone.now)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self) -> str:
        return f'{self.routine.name}-{self.exercise.name}'


class Set(models.Model):
    weight = models.FloatField()
    repetition = models.PositiveIntegerField()
    workout = models.ForeignKey(Workout, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f'{self.workout.routine.name}-{self.workout.exercise.name} set: {self.id}'
     
     
class Done(models.Model):

    set = models.OneToOneField(Set, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

ChatBot_Website_Project/Mamoon/workouts/forms.py
from django import forms
from .models import Workout


class WorkoutForm(forms.ModelForm):
    class Meta:
        model = Workout
        fields = ['exercise', 'note']

  

ChatBot_Website_Project/Mamoon/workouts/views.py
from django.shortcuts import render, redirect
from django.http import HttpRequest, HttpResponse

from .forms import WorkoutForm
from .models import Workout, Set, Done

from routines.models import Routine

from exercises.models import Exercise

from django.contrib import messages


def new_workout_view(request: HttpRequest, routine_id: int):
    routine = Routine.objects.get(pk=routine_id)
    
    workout_form = WorkoutForm()

    if request.method == "POST":
        workout_form = WorkoutForm(request.POST)
        if workout_form.is_valid():
            workout = workout_form.save(commit=False)
            if request.POST["restTime"].isdigit():
                workout.restTime = int(request.POST["restTime"])
                workout.routine = routine
                workout.save()
                if request.POST.get("repetition", "").strip():
                    if request.POST['repetition'].isdigit():
                        weight = request.POST["weight"]
                        try:
                            weight = float(weight) 
                            if weight <= 0:
                                messages.error(request, "Weight must be a positive number.", "alert-danger")
                            else:
                                new_set = Set(weight=weight, repetition=int(request.POST['repetition']), workout=workout)
                                new_set.save()
                                messages.success(request, "Workout added successfully!", "alert-success")
                                
                        except ValueError:
                            messages.error(request, "Weight must be a valid number.", "alert-danger")
                    else:
                        messages.error(request, "Repetition must be digit number. Please correct the errors.", "alert-danger")
                else:
                    messages.error(request, "Repetition must be digit number. Please correct the errors.", "alert-danger")
            else:
                messages.error(request, "Rest Time must be digit number. Please correct the errors.", "alert-danger")
        else:
            messages.error(request, "There is an error in the form. Please correct the errors.", "alert-danger")
            
    else:
        messages.error(request, "There are no data received. Please correct the errors.", "alert-danger")

    return redirect("routines:routine_detail_view", routine_id=routine_id)


def update_workout_view(request:HttpRequest, workout_id:int):
    workout = Workout.objects.get(pk=workout_id)
    routine = Routine.objects.get(pk=workout.routine.id)
    exercises = Exercise.objects.all()

    if request.method == "POST":
        if request.POST["restTime"]:
            if request.POST["restTime"].isdigit():
                workout.restTime = int(request.POST["restTime"])
                workout.note = request.POST.get("note", "").strip()
                updated_exercise = Exercise.objects.get(pk=int(request.POST['exercise']))
                workout.exercise = updated_exercise
                workout.save()
                messages.success(request, "Updated Workout Successfuly!", "alert-success")
                return redirect("routines:routine_detail_view", routine_id=workout.routine.id)
            else:
                messages.error(request, "Rest Time must be digit number. Please correct the errors.", "alert-danger")
            
        else:
            messages.error(request, "There are no data received. Please correct the errors.", "alert-danger")

    return render(
        request,"workouts/update_workout.html",
        {
            "routine": routine,
            'workout':workout,
            'exercises': exercises,
        },
    )


def delete_workout_view(request:HttpRequest,  workout_id:int):
    try:
        workout = Workout.objects.get(pk=workout_id)
        workout.delete()
        messages.success(request, "Deleted Workout Successfuly!", "alert-success")
    except Exception as e:
        print(e)
        messages.error(request, "Couldn't Delete Workout!", "alert-danger")
    
    return redirect("main:home_view")


def new_set_view(request:HttpRequest, workout_id:int):
    
    if request.method == "POST":
        workout = Workout.objects.get(pk=workout_id)
                
        if request.POST['repetition'].isdigit():
            weight = request.POST["weight"]
            try:
                weight = float(weight) 
                if weight <= 0:
                    messages.error(request, "Weight must be a positive number.", "alert-danger")
                else:
                    new_set = Set(weight=weight, repetition=int(request.POST['repetition']), workout=workout)
                    new_set.save()
                    messages.success(request, "Added Set Successfuly!", "alert-success")
            except ValueError:
                messages.error(request, "Weight must be a valid number.", "alert-danger")
        else:
            messages.error(request, "Couldn't Add Set! Please insert correct numbers.", "alert-danger")
            
    else:
        messages.error(request, "Couldn't Add Set!. Please correct the errors.", "alert-danger")
    
    return redirect("routines:routine_detail_view", routine_id=workout.routine.id)




def update_set_view(request, set_id):
    if request.method == "POST":
        set_obj = Set.objects.get(pk=set_id)
        
        if request.POST['repetition'].isdigit():
            weight = request.POST["weight"]
            try:
                weight = float(weight) 
                if weight <= 0:
                    messages.error(request, "Weight must be a positive number.", "alert-danger")
                else:
                    set_obj.weight = weight
                    set_obj.repetition = request.POST['repetition']
                    set_obj.save()
                    messages.success(request, "The set updated successfully!", "alert-success")
            except ValueError:
                messages.error(request, "Weight must be a valid number.", "alert-danger")
        else:
            messages.error(request, "Repetition must be a digit.", "alert-danger")
           
    else:
        messages.error(request, "Couldn't Update Set!. Please correct the errors.", "alert-danger")

    return redirect("routines:routine_detail_view", routine_id=set_obj.workout.routine.id)


def delete_set_view(request:HttpRequest, set_id:int):
    try:
        set = Set.objects.get(pk=set_id)
        set.delete()
        messages.success(request, f"{set.workout.exercise.name} set {set.id} Deleted Successfuly!", "alert-success")
    except Exception as e:
        print(e)
        messages.error(request, "Couldn't Delete Set!", "alert-danger")
    
    return redirect("routines:routine_detail_view", routine_id=set.workout.routine.id)



def done_set_view(request: HttpRequest, set_id:int):
    workout_set = Set.objects.get(pk=set_id)
    try:

        done = Done.objects.filter(set=workout_set).first() 
        if not done:
            new_done = Done(set=workout_set)
            new_done.save()
            messages.success(request, "Set Done!", "alert-success")
        else:
            done.delete()
            messages.error(request, "Set Undone!", "alert-danger")

    except Set.DoesNotExist:
        messages.error(request, "Set not found.")
    except Exception as e:
        messages.error(request, "An error occurred: " + str(e))

    return redirect("routines:routine_detail_view", routine_id=workout_set.workout.routine.id)



def finish_workout_view(request: HttpRequest, workout_id: int):
    try:
        workout = Workout.objects.get(pk=workout_id)
        sets = workout.set_set.all()  

        for set_obj in sets:
            done = Done.objects.filter(set=set_obj).first()
            if done:
                done.delete()

        messages.success(request, f"All sets have been reset to 'Undone' for {workout.exercise.name} workout.", "alert-success")

    except Workout.DoesNotExist:
        messages.error(request, "Workout not found.", "alert-danger")
    except Exception as e:
        messages.error(request, f"An error occurred: {e}", "alert-danger")

    return redirect("routines:routine_detail_view", routine_id=workout.routine.id)



    
    
    


    
    
    

ChatBot_Website_Project/Mamoon/workouts/templates/workouts/update_workout.html
{% extends 'main/base.html' %}

{% block title %} Update Workout {% endblock %}

{% block content %}

{% load static %}

<div class="d-flex flex-column justify-content-center align-items-center">

    <div class="row justify-content-center w-100">
        <div class="col-12 col-sm-10 col-lg-5">
            <form class="d-flex flex-column gap-4" action="{% url 'workouts:update_workout_view' workout.id %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="d-flex flex-column mb-5" style="width: 100%;">
                    <h1 class="text-sm-center">Routine: {{ routine.name }}</h1>
                </div>
                <div class="transparent-bg">
                    <h2>Update {{ workout.exercise.name }} Exercise</h2>
                    <div class="d-flex flex-column gap-3 border p-3 rounded">
                        <div class="d-flex flex-column gap-1 mb-5">
                            <label for="exercise">Select Exercise To Workout On</label>
                            <div class="dropdown">
                                <button class="btn btn-light dropdown-toggle w-100" type="button" id="exerciseDropdown" data-bs-toggle="dropdown">
                                    {{ workout.exercise.name }}
                                </button>
                                <ul class="dropdown-menu w-100" aria-labelledby="exerciseDropdown" style="max-height: 300px; overflow-y: auto;">
                                    {% for exercise in exercises %} 
                                        <li>
                                            <input type="radio" name="exercise" id="exercise_{{ exercise.id }}" value="{{ exercise.id }}" class="d-none" {% if workout.exercise.id == exercise.id %} checked {% endif %} >
                                            <label for="exercise_{{ exercise.id }}" class="label-bg dropdown-item d-flex align-items-center gap-3">
                                                <img src="{{ exercise.image.url }}" class="rounded" style="width: 80px; height: 80px; object-fit: cover;">
                                                {{ exercise.name }}
                                            </label>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
    
                        <div class="d-flex flex-column gap-1">
                            <label for="note">Workout Note <span class="text-white">(optional)</span></label>
                            <textarea name="note" id="note" class="form-control">{{ workout.note }}</textarea>
                        </div>
    
                        <div class="d-flex flex-column gap-1">
                            <label for="restTime">Rest Time (in seconds)</label>
                            <input type="number" name="restTime" id="restTime" value="{{ workout.restTime }}" placeholder="e.g., 30" class="form-control" /> 
                        </div>

                    </div>
                </div>

                <input type="submit" value="Update Workout" class="btn form-control" style="background-color: #fcd15c; color: black"/>
            </form>
        </div>
    </div>
</div>

{% endblock %}